USE ROLE USERADMIN;

CREATE ROLE DATAADMIN ;
CREATE ROLE SVC;

CREATE USER TRF_SVC WITH PASSWORD= 'SNOWFLAKE@123snowflake';
CREATE USER DATAADMIN WITH PASSWORD= 'SNOWFLAKE@123snowflake';

USE ROLE SECURITYADMIN;

GRANT ROLE DATAADMIN TO USER DATAADMIN;
GRANT ROLE DATAADMIN TO USER QRIOUSTRAINING;
GRANT ROLE SVC TO USER TRF_SVC;


USE ROLE SYSADMIN;

CREATE DATABASE Raw;
CREATE SCHEMA Raw.POS;
CREATE DATABASE Retail;
CREATE SCHEMA Retail.STG;
CREATE SCHEMA Retail.TRF;
CREATE SCHEMA Retail.DWH;

USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE  COMPUTE_WH TO ROLE DATAADMIN;
GRANT USAGE ON WAREHOUSE  COMPUTE_WH TO ROLE svc;

GRANT USAGE ON database Raw TO ROLE DATAADMIN;
GRANT USAGE ON database Raw TO ROLE svc;

GRANT USAGE ON SCHEMA Raw.POS TO ROLE DATAADMIN;
GRANT USAGE ON SCHEMA Raw.POS TO ROLE svc;


GRANT SELECT ON ALL TABLES IN SCHEMA Raw.POS TO ROLE DATAADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA Raw.POS TO ROLE svc;


GRANT USAGE ON database Retail TO ROLE DATAADMIN;
GRANT USAGE ON database Retail TO ROLE svc;


GRANT USAGE ON SCHEMA Retail.STG TO ROLE DATAADMIN;
GRANT ALL ON FUTURE TABLES IN SCHEMA Retail.STG TO ROLE DATAADMIN;

GRANT USAGE on SCHEMA Retail.STG TO ROLE SVC;
GRANT ALL ON FUTURE TABLES IN SCHEMA Retail.STG TO ROLE SVC;

GRANT USAGE ON SCHEMA Retail.TRF TO ROLE DATAADMIN;
GRANT ALL ON FUTURE TABLES IN SCHEMA Retail.TRF TO ROLE DATAADMIN;

GRANT USAGE on SCHEMA Retail.TRF TO ROLE SVC;
GRANT ALL ON FUTURE TABLES IN SCHEMA Retail.TRF TO ROLE SVC;

GRANT USAGE ON SCHEMA Retail.DWH TO ROLE DATAADMIN;
GRANT ALL ON FUTURE TABLES IN SCHEMA Retail.DWH TO ROLE DATAADMIN;

GRANT USAGE on SCHEMA Retail.DWH TO ROLE SVC;
GRANT ALL ON FUTURE TABLES IN SCHEMA Retail.DWH TO ROLE SVC;

USE ROLE DATAADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE TABLE Raw.POS.CUSTOMER LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
INSERT INTO RAW.POS.CUSTOMER SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE TABLE RAW.POS.NATION LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
INSERT INTO RAW.POS.NATION SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

CREATE TABLE RAW.POS.ORDERS LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
INSERT INTO RAW.POS.ORDERS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

CREATE TABLE RAW.POS.LINEITEM LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
INSERT INTO RAW.POS.LINEITEM SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

CREATE TABLE RAW.POS.PART LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;
INSERT INTO RAW.POS.PART SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

CREATE TABLE RAW.POS.PARTSUPP LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;
INSERT INTO RAW.POS.PARTSUPP SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;

-- Clone Prod env to DEV
USE ROLE SYSADMIN;
CREATE DATABASE RETAIL_DEV CLONE RETAIL;

GRANT USAGE ON database Retail_DEV TO ROLE DATAADMIN;
GRANT USAGE ON database Retail_DEV TO ROLE svc;
 
 
